// // Code generated by Excel2ScriptableObject. DO NOT EDIT.
// using System.Linq;
// using GoPlay.Data.Config;
// using GoPlay.Managers;
//
// namespace GoPlay.Systems.Translate
// {
//     public partial class LangSystem
//     {
//         public static string[] Languages
//         {
//             get;
//         }
//
//         protected override void OnInitialize()
//         {
//             base.OnInitialize();
//
//             IsReady = true;
//         }
//     }
// }